import os
import requests
from PIL import Image
import io
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'nexus_backend.settings')
django.setup()

from django.contrib.auth import get_user_model
from store.models import Category, Product, Review

User = get_user_model()

# Ensure destination directory exists
DEST_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'frontend', 'public', 'images', 'products', 'laptops')
os.makedirs(DEST_DIR, exist_ok=True)

print(f"Target directory for laptop images: {DEST_DIR}")

# 50 Detailed Laptop Products
LAPTOPS = [
    # --- DELL (10) ---
    {
        "name": "Dell XPS 13",
        "brand": "Dell",
        "price": 1299.00,
        "filename": "dell-xps-13.webp",
        "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Ultra-portable 13.4-inch flagship with CNC aluminum body and Intel Core Ultra 7 processor.",
        "full_desc": "The Dell XPS 13 redefines ultra-portable computing. Crafted from premium CNC machined aluminum with a Gorilla Glass 3 palm rest and futuristic touch function row, it delivers powerful performance in a remarkably thin 13.4-inch chassis.",
        "specs": {
            "SKU": "DELL-XPS13-9340",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5X 7467MHz",
            "Storage": "512GB PCIe NVMe M.2 SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "13.4 inches",
            "Resolution": "1920 x 1200 FHD+",
            "Refresh Rate": "120Hz Variable",
            "Operating System": "Windows 11 Home",
            "Battery": "55Wh (Up to 18 Hours)",
            "Weight": "2.6 lbs (1.19 kg)",
            "Color": "Platinum",
            "Warranty": "1-Year Dell Premium Support",
            "Discount": "10%"
        },
        "stock_qty": 45,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 128
    },
    {
        "name": "Dell XPS 14",
        "brand": "Dell",
        "price": 1699.00,
        "filename": "dell-xps-14.webp",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Perfect balance of power and mobility featuring 3.2K OLED display and RTX 4050 graphics.",
        "full_desc": "Designed for creators and power users, the Dell XPS 14 combines a stunning 3.2K OLED InfinityEdge touch screen with dedicated NVIDIA GeForce RTX 4050 graphics for seamless video editing and 3D rendering on the go.",
        "specs": {
            "SKU": "DELL-XPS14-9440",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "32GB LPDDR5X",
            "Storage": "1TB PCIe Gen4 NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "14.5 inches",
            "Resolution": "3200 x 2000 3.2K OLED Touch",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "69.5Wh",
            "Weight": "3.8 lbs (1.72 kg)",
            "Color": "Graphite",
            "Warranty": "1-Year Dell Premium Support",
            "Discount": "5%"
        },
        "stock_qty": 30,
        "is_featured": True,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 84
    },
    {
        "name": "Dell XPS 16",
        "brand": "Dell",
        "price": 2499.00,
        "filename": "dell-xps-16.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Flagship 16-inch performance laptop with Core Ultra 9, 4K+ OLED screen, and RTX 4070 GPU.",
        "full_desc": "The ultimate expression of laptop engineering. Dell XPS 16 boasts a massive 16.3-inch 4K+ OLED display, Intel Core Ultra 9 processor, and studio-grade quad speakers with Waves MaxxAudio.",
        "specs": {
            "SKU": "DELL-XPS16-9640",
            "Processor": "Intel Core Ultra 9 185H",
            "RAM": "32GB LPDDR5X",
            "Storage": "1TB PCIe Gen4 NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4070 8GB",
            "Display Size": "16.3 inches",
            "Resolution": "3840 x 2400 4K+ OLED",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "99.5Wh",
            "Weight": "4.7 lbs (2.13 kg)",
            "Color": "Platinum",
            "Warranty": "2-Year Dell ProSupport",
            "Discount": "15%"
        },
        "stock_qty": 20,
        "is_featured": True,
        "is_new": False,
        "rating": 4.9,
        "num_reviews": 62
    },
    {
        "name": "Dell Inspiron 14",
        "brand": "Dell",
        "price": 649.00,
        "filename": "dell-inspiron-14.webp",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Compact everyday 14-inch laptop with Intel Core 7 processor and all-day battery life.",
        "full_desc": "Empower your daily tasks with Dell Inspiron 14. Featuring express charge technology, dual noise-canceling digital microphones, and a full HD+ 16:10 display for enhanced productivity.",
        "specs": {
            "SKU": "DELL-INS14-5440",
            "Processor": "Intel Core 7 150U",
            "RAM": "16GB DDR5 5200MHz",
            "Storage": "512GB NVMe M.2 SSD",
            "GPU": "Intel Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 FHD+",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "54Wh",
            "Weight": "3.4 lbs (1.54 kg)",
            "Color": "Ice Blue",
            "Warranty": "1-Year Basic Mail-in",
            "Discount": "8%"
        },
        "stock_qty": 60,
        "is_featured": False,
        "is_new": False,
        "rating": 4.5,
        "num_reviews": 95
    },
    {
        "name": "Dell Inspiron 15",
        "brand": "Dell",
        "price": 599.00,
        "filename": "dell-inspiron-15.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Reliable 15.6-inch workhorse with 120Hz Full HD display and spacious keyboard layout.",
        "full_desc": "A classic 15.6-inch laptop built for comfort and efficiency. Features a numeric keypad, lift-hinge design for ergonomic typing, and 120Hz refresh rate for smooth scrolling.",
        "specs": {
            "SKU": "DELL-INS15-3530",
            "Processor": "Intel Core i5-1335U",
            "RAM": "16GB DDR4",
            "Storage": "512GB NVMe SSD",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "41Wh",
            "Weight": "3.6 lbs (1.63 kg)",
            "Color": "Carbon Black",
            "Warranty": "1-Year Hardware Warranty",
            "Discount": "12%"
        },
        "stock_qty": 75,
        "is_featured": False,
        "is_new": False,
        "rating": 4.4,
        "num_reviews": 110
    },
    {
        "name": "Dell Inspiron 16 Plus",
        "brand": "Dell",
        "price": 1199.00,
        "filename": "dell-inspiron-16-plus.webp",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "High-performance 16-inch laptop with 2.5K display and RTX 4050 discrete graphics.",
        "full_desc": "Level up your creative workflow with Inspiron 16 Plus. Equipped with an expansive 2.5K display, Dolby Atmos spatial audio, and NVIDIA Studio drivers for optimized creativity.",
        "specs": {
            "SKU": "DELL-INS16P-7640",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5X",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 2.5K",
            "Refresh Rate": "90Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "90Wh",
            "Weight": "4.6 lbs (2.08 kg)",
            "Color": "Ice Blue",
            "Warranty": "1-Year Premium Support",
            "Discount": "10%"
        },
        "stock_qty": 40,
        "is_featured": False,
        "is_new": True,
        "rating": 4.7,
        "num_reviews": 52
    },
    {
        "name": "Dell Latitude 5440",
        "brand": "Dell",
        "price": 1099.00,
        "filename": "dell-latitude-5440.webp",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Commercial 14-inch business laptop with vPro management and enterprise security.",
        "full_desc": "Engineered for business professionals. Dell Latitude 5440 features hardware-level security, AI-tuned audio clarity, dual Thunderbolt 4 ports, and long battery runtime.",
        "specs": {
            "SKU": "DELL-LAT5440-ENT",
            "Processor": "Intel Core i7-1365U vPro",
            "RAM": "16GB DDR5",
            "Storage": "512GB NVMe SSD Class 35",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1080 FHD Anti-Glare",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "54Wh ExpressCharge",
            "Weight": "3.06 lbs (1.39 kg)",
            "Color": "Titan Grey",
            "Warranty": "3-Year Dell ProSupport",
            "Discount": "0%"
        },
        "stock_qty": 50,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 48
    },
    {
        "name": "Dell Latitude 7440",
        "brand": "Dell",
        "price": 1449.00,
        "filename": "dell-latitude-7440.webp",
        "image_url": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Ultra-lightweight enterprise laptop with QHD+ touch display and aluminum chassis.",
        "full_desc": "Premium executive portability. The Latitude 7440 features a ultralight aluminum chassis, QHD+ 16:10 touch display, quad speakers, and intelligent thermal management.",
        "specs": {
            "SKU": "DELL-LAT7440-ULTR",
            "Processor": "Intel Core i7-1370P vPro",
            "RAM": "32GB LPDDR5",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "2560 x 1600 QHD+ Touch",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "57Wh",
            "Weight": "2.93 lbs (1.33 kg)",
            "Color": "Aluminum Titan",
            "Warranty": "3-Year ProSupport Plus",
            "Discount": "5%"
        },
        "stock_qty": 35,
        "is_featured": False,
        "is_new": False,
        "rating": 4.8,
        "num_reviews": 39
    },
    {
        "name": "Dell Precision 3590",
        "brand": "Dell",
        "price": 1799.00,
        "filename": "dell-precision-3590.webp",
        "image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "ISV-certified mobile workstation with NVIDIA RTX 500 Ada professional graphics.",
        "full_desc": "Built for CAD design, video editing, and software development. The Dell Precision 3590 features ISV certifications, Intel Core Ultra 7 vPro, and NVIDIA Ada generation professional GPUs.",
        "specs": {
            "SKU": "DELL-PREC3590-WS",
            "Processor": "Intel Core Ultra 7 165H vPro",
            "RAM": "32GB DDR5 5600MHz",
            "Storage": "1TB PCIe Gen4 SSD",
            "GPU": "NVIDIA RTX 500 Ada 4GB GDDR6",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD 100% sRGB",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro Workstations",
            "Battery": "54Wh",
            "Weight": "3.58 lbs (1.62 kg)",
            "Color": "Titan Grey",
            "Warranty": "3-Year Onsite Service",
            "Discount": "7%"
        },
        "stock_qty": 25,
        "is_featured": False,
        "is_new": True,
        "rating": 4.7,
        "num_reviews": 29
    },
    {
        "name": "Dell Alienware m18",
        "brand": "Dell",
        "price": 2899.00,
        "filename": "dell-alienware-m18.webp",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Extreme 18-inch desktop replacement gaming rig with RTX 4090 and i9-14900HX.",
        "full_desc": "Unrivaled gaming dominance. Alienware m18 features an colossal 18-inch QHD+ 165Hz display, Element 31 quad-fan cooling system, Cherry MX mechanical keyboard, and RTX 4090 16GB graphics.",
        "specs": {
            "SKU": "DELL-AW-M18-R2",
            "Processor": "Intel Core i9-14900HX",
            "RAM": "64GB DDR5 5600MHz",
            "Storage": "2TB PCIe NVMe RAID 0 SSD",
            "GPU": "NVIDIA GeForce RTX 4090 16GB",
            "Display Size": "18.0 inches",
            "Resolution": "2560 x 1600 QHD+",
            "Refresh Rate": "165Hz 3ms G-Sync",
            "Operating System": "Windows 11 Home",
            "Battery": "97Wh",
            "Weight": "8.9 lbs (4.04 kg)",
            "Color": "Dark Metallic Moon",
            "Warranty": "1-Year Alienware Premium Support",
            "Discount": "15%"
        },
        "stock_qty": 18,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 76
    },

    # --- HP (10) ---
    {
        "name": "HP Spectre x360 14",
        "brand": "HP",
        "price": 1449.00,
        "filename": "hp-spectre-x360-14.webp",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "2-in-1 convertible ultrabook with 2.8K OLED touch screen and AI noise cancellation.",
        "full_desc": "Crafted from gem-cut aluminum, the HP Spectre x360 14 transitions seamlessly from laptop to tablet mode. Includes an IMAX Enhanced 2.8K OLED touch screen and 9MP AI glare-free camera.",
        "specs": {
            "SKU": "HP-SPEC14-2IN1",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5x",
            "Storage": "1TB PCIe Gen4 NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED Touch",
            "Refresh Rate": "120Hz Variable",
            "Operating System": "Windows 11 Home",
            "Battery": "68Wh (Up to 13 Hours)",
            "Weight": "3.19 lbs (1.44 kg)",
            "Color": "Nightfall Black",
            "Warranty": "1-Year HP Limited Warranty",
            "Discount": "10%"
        },
        "stock_qty": 40,
        "is_featured": True,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 92
    },
    {
        "name": "HP Spectre x360 16",
        "brand": "HP",
        "price": 1799.00,
        "filename": "hp-spectre-x360-16.webp",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Expansive 16-inch 2-in-1 convertible with RTX 4050 GPU and quad quad-firing speakers.",
        "full_desc": "Creativity without bounds. HP Spectre x360 16 offers a massive 16-inch touch canvas with NVIDIA RTX 4050 graphics and Poly Studio quad audio system.",
        "specs": {
            "SKU": "HP-SPEC16-2IN1",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "32GB LPDDR5x",
            "Storage": "2TB PCIe Gen4 NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "16.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED Touch",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "83Wh",
            "Weight": "4.3 lbs (1.95 kg)",
            "Color": "Slate Blue",
            "Warranty": "1-Year HP Onsite Warranty",
            "Discount": "5%"
        },
        "stock_qty": 28,
        "is_featured": False,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 64
    },
    {
        "name": "HP ENVY x360 14",
        "brand": "HP",
        "price": 849.00,
        "filename": "hp-envy-x360-14.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Versatile 14-inch 2-in-1 laptop powered by AMD Ryzen 7 8840HS with AI boost.",
        "full_desc": "Adapt to work or play with HP ENVY x360 14. Features 360-degree hinge, AMD Ryzen AI graphics processing, and fast charging up to 50% in 30 minutes.",
        "specs": {
            "SKU": "HP-ENVY14-2IN1",
            "Processor": "AMD Ryzen 7 8840HS",
            "RAM": "16GB LPDDR5",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "AMD Radeon 780M",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 FHD+ Touch",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "59Wh",
            "Weight": "3.08 lbs (1.39 kg)",
            "Color": "Glacier Silver",
            "Warranty": "1-Year Express Warranty",
            "Discount": "12%"
        },
        "stock_qty": 55,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 71
    },
    {
        "name": "HP ENVY 16",
        "brand": "HP",
        "price": 1399.00,
        "filename": "hp-envy-16.webp",
        "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Content creator laptop with 16-inch WQXGA 120Hz panel and RTX 4060 GPU.",
        "full_desc": "Engineered for video production and digital design. HP ENVY 16 features dual thermal fans, vapor chamber cooling, and calibrated color accuracy with Eyesafe certification.",
        "specs": {
            "SKU": "HP-ENVY16-2024",
            "Processor": "Intel Core i7-13700H",
            "RAM": "16GB DDR5 5200MHz",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4060 8GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 WQXGA",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "83Wh",
            "Weight": "5.9 lbs (2.67 kg)",
            "Color": "Natural Silver",
            "Warranty": "1-Year Premium Warranty",
            "Discount": "15%"
        },
        "stock_qty": 35,
        "is_featured": False,
        "is_new": False,
        "rating": 4.7,
        "num_reviews": 48
    },
    {
        "name": "HP Pavilion 15",
        "brand": "HP",
        "price": 629.00,
        "filename": "hp-pavilion-15.webp",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Affordable 15.6-inch laptop with micro-edge display and Audio by B&O.",
        "full_desc": "Everyday laptop perfection. HP Pavilion 15 delivers solid everyday performance with B&O custom audio tuning, fast Wi-Fi 6 connectivity, and micro-edge bezel design.",
        "specs": {
            "SKU": "HP-PAV15-EG3",
            "Processor": "Intel Core i5-1335U",
            "RAM": "16GB DDR4",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "41Wh",
            "Weight": "3.86 lbs (1.75 kg)",
            "Color": "Fog Blue",
            "Warranty": "1-Year Hardware Warranty",
            "Discount": "10%"
        },
        "stock_qty": 80,
        "is_featured": False,
        "is_new": False,
        "rating": 4.5,
        "num_reviews": 140
    },
    {
        "name": "HP Pavilion Plus 14",
        "brand": "HP",
        "price": 899.00,
        "filename": "hp-pavilion-plus-14.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Sleek 14-inch ultrabook with 2.8K 120Hz OLED screen and Ryzen 7 7840U.",
        "full_desc": "Compact power with a visual punch. HP Pavilion Plus 14 pairs an ultra-vivid 2.8K OLED screen with all-metal recycled aluminum casing and 5MP IR webcam.",
        "specs": {
            "SKU": "HP-PAVPLUS14-OLED",
            "Processor": "AMD Ryzen 7 7840U",
            "RAM": "16GB LPDDR5x",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "AMD Radeon 780M",
            "Display Size": "14.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "68Wh",
            "Weight": "3.04 lbs (1.38 kg)",
            "Color": "Moonlight Blue",
            "Warranty": "1-Year Limited Warranty",
            "Discount": "8%"
        },
        "stock_qty": 45,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 67
    },
    {
        "name": "HP Victus 15",
        "brand": "HP",
        "price": 799.00,
        "filename": "hp-victus-15.webp",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Mainstream gaming laptop with 144Hz FHD screen and RTX 4050 graphics.",
        "full_desc": "Ready for high-octane gaming. HP Victus 15 equips gamers with a 144Hz high refresh rate screen, OMEN Gaming Hub software controls, and dual fan thermal management.",
        "specs": {
            "SKU": "HP-VICTUS15-GAM",
            "Processor": "AMD Ryzen 5 7535HS",
            "RAM": "16GB DDR5 4800MHz",
            "Storage": "512GB PCIe Gen4 SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "144Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "70Wh",
            "Weight": "5.06 lbs (2.29 kg)",
            "Color": "Mica Silver",
            "Warranty": "1-Year HP Gaming Warranty",
            "Discount": "15%"
        },
        "stock_qty": 65,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 115
    },
    {
        "name": "HP OMEN 16",
        "brand": "HP",
        "price": 1599.00,
        "filename": "hp-omen-16.webp",
        "image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "High-end 16-inch esports laptop with 240Hz QHD display and RTX 4070 GPU.",
        "full_desc": "Elite gaming gear. HP OMEN 16 features Tempest Cooling technology, per-key RGB optical mechanical keyboard, 240Hz competitive screen, and DTS:X Ultra audio.",
        "specs": {
            "SKU": "HP-OMEN16-WF",
            "Processor": "Intel Core i7-14700HX",
            "RAM": "32GB DDR5 5600MHz",
            "Storage": "1TB PCIe Gen4 NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4070 8GB",
            "Display Size": "16.1 inches",
            "Resolution": "2560 x 1440 QHD IPS",
            "Refresh Rate": "240Hz 3ms",
            "Operating System": "Windows 11 Home",
            "Battery": "83Wh",
            "Weight": "5.4 lbs (2.45 kg)",
            "Color": "Shadow Black",
            "Warranty": "1-Year OMEN VIP Support",
            "Discount": "10%"
        },
        "stock_qty": 30,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 88
    },
    {
        "name": "HP EliteBook 840 G11",
        "brand": "HP",
        "price": 1649.00,
        "filename": "hp-elitebook-840-g11.webp",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Premium enterprise 14-inch notebook with HP Wolf Security and vPro processor.",
        "full_desc": "Designed for enterprise mobility and zero-trust environments. The HP EliteBook 840 G11 features HP Sure Start self-healing BIOS, 5MP IR camera with privacy shutter, and all-metal magnesium design.",
        "specs": {
            "SKU": "HP-ELITE840-G11",
            "Processor": "Intel Core Ultra 7 165H vPro",
            "RAM": "32GB DDR5",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 WUXGA Anti-Glare",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "56Wh",
            "Weight": "3.1 lbs (1.41 kg)",
            "Color": "Pike Silver",
            "Warranty": "3-Year Next Business Day Onsite",
            "Discount": "0%"
        },
        "stock_qty": 40,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 42
    },
    {
        "name": "HP ProBook 450 G10",
        "brand": "HP",
        "price": 949.00,
        "filename": "hp-probook-450-g10.webp",
        "image_url": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Durable 15.6-inch business notebook with commercial security and expandable RAM.",
        "full_desc": "Growing business reliability. HP ProBook 450 G10 features military-grade MIL-STD 810H durability testing, dual SODIMM expansion slots, and spill-resistant keyboard.",
        "specs": {
            "SKU": "HP-PROBOOK450-G10",
            "Processor": "Intel Core i7-1355U",
            "RAM": "16GB DDR4",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "51Wh",
            "Weight": "3.96 lbs (1.79 kg)",
            "Color": "Pike Silver",
            "Warranty": "1-Year Commercial Warranty",
            "Discount": "5%"
        },
        "stock_qty": 60,
        "is_featured": False,
        "is_new": False,
        "rating": 4.5,
        "num_reviews": 56
    },

    # --- APPLE MACBOOK (10) ---
    {
        "name": "MacBook Air 13-inch (M2)",
        "brand": "Apple",
        "price": 999.00,
        "filename": "macbook-air-13-m2.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Redesigned ultra-thin 13.6-inch laptop with Apple M2 chip and MagSafe charging.",
        "full_desc": "Strikingly thin and fast. MacBook Air 13 with M2 chip features an all-aluminum unibody enclosure, Liquid Retina display with 500 nits brightness, 1080p FaceTime HD camera, and up to 18 hours of battery life.",
        "specs": {
            "SKU": "APPL-MBA13-M2",
            "Processor": "Apple M2 (8-Core CPU / 8-Core GPU)",
            "RAM": "8GB Unified Memory",
            "Storage": "256GB High-Speed SSD",
            "GPU": "Apple 8-Core Integrated GPU",
            "Display Size": "13.6 inches",
            "Resolution": "2560 x 1664 Liquid Retina",
            "Refresh Rate": "60Hz True Tone",
            "Operating System": "macOS Sonoma",
            "Battery": "52.6Wh (Up to 18 Hours)",
            "Weight": "2.7 lbs (1.24 kg)",
            "Color": "Midnight",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "10%"
        },
        "stock_qty": 90,
        "is_featured": True,
        "is_new": False,
        "rating": 4.9,
        "num_reviews": 230
    },
    {
        "name": "MacBook Air 15-inch (M2)",
        "brand": "Apple",
        "price": 1199.00,
        "filename": "macbook-air-15-m2.webp",
        "image_url": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Spacious 15.3-inch liquid retina display ultrabook with six-speaker sound system.",
        "full_desc": "Impressively big. Impossibly thin. MacBook Air 15 with M2 chip gives you more room for what you love with a spacious 15.3-inch Liquid Retina display and immersive six-speaker sound system with Spatial Audio.",
        "specs": {
            "SKU": "APPL-MBA15-M2",
            "Processor": "Apple M2 (8-Core CPU / 10-Core GPU)",
            "RAM": "16GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 10-Core GPU",
            "Display Size": "15.3 inches",
            "Resolution": "2880 x 1864 Liquid Retina",
            "Refresh Rate": "60Hz",
            "Operating System": "macOS Sonoma",
            "Battery": "66.5Wh (Up to 18 Hours)",
            "Weight": "3.3 lbs (1.51 kg)",
            "Color": "Starlight",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "8%"
        },
        "stock_qty": 70,
        "is_featured": False,
        "is_new": False,
        "rating": 4.8,
        "num_reviews": 175
    },
    {
        "name": "MacBook Air 13-inch (M3)",
        "brand": "Apple",
        "price": 1099.00,
        "filename": "macbook-air-13-m3.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Next-gen 13.6-inch laptop with M3 chip, hardware ray tracing, and dual external monitor support.",
        "full_desc": "Lean. Mean. M3 machine. MacBook Air 13 with M3 chip unleashes enhanced performance, hardware-accelerated ray tracing, Wi-Fi 6E, and support for up to two external displays when closed.",
        "specs": {
            "SKU": "APPL-MBA13-M3",
            "Processor": "Apple M3 (8-Core CPU / 8-Core GPU)",
            "RAM": "16GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 8-Core GPU with Ray Tracing",
            "Display Size": "13.6 inches",
            "Resolution": "2560 x 1664 Liquid Retina",
            "Refresh Rate": "60Hz",
            "Operating System": "macOS Sequoia",
            "Battery": "52.6Wh (Up to 18 Hours)",
            "Weight": "2.7 lbs (1.24 kg)",
            "Color": "Space Gray",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "5%"
        },
        "stock_qty": 85,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 195
    },
    {
        "name": "MacBook Air 15-inch (M3)",
        "brand": "Apple",
        "price": 1299.00,
        "filename": "macbook-air-15-m3.webp",
        "image_url": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Expansive 15.3-inch ultrabook powered by Apple M3 chip with anodization seal against fingerprints.",
        "full_desc": "The ultimate 15-inch consumer laptop. Featuring Apple M3 silicon, breakthrough battery efficiency, dual display output, and a breakthrough anti-fingerprint anodization coating on Midnight model.",
        "specs": {
            "SKU": "APPL-MBA15-M3",
            "Processor": "Apple M3 (8-Core CPU / 10-Core GPU)",
            "RAM": "16GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 10-Core GPU",
            "Display Size": "15.3 inches",
            "Resolution": "2880 x 1864 Liquid Retina",
            "Refresh Rate": "60Hz",
            "Operating System": "macOS Sequoia",
            "Battery": "66.5Wh (Up to 18 Hours)",
            "Weight": "3.3 lbs (1.51 kg)",
            "Color": "Midnight",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "5%"
        },
        "stock_qty": 65,
        "is_featured": False,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 140
    },
    {
        "name": "MacBook Pro 14-inch (M3)",
        "brand": "Apple",
        "price": 1599.00,
        "filename": "macbook-pro-14-m3.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Pro performance 14.2-inch laptop with Liquid Retina XDR display and 120Hz ProMotion.",
        "full_desc": "Mind-blowing Pro performance. The 14-inch MacBook Pro with M3 features a Liquid Retina XDR screen with 1600 nits peak HDR brightness, HDMI port, SDXC card slot, and up to 22 hours battery runtime.",
        "specs": {
            "SKU": "APPL-MBP14-M3",
            "Processor": "Apple M3 (8-Core CPU / 10-Core GPU)",
            "RAM": "16GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 10-Core GPU",
            "Display Size": "14.2 inches",
            "Resolution": "3024 x 1964 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "70Wh (Up to 22 Hours)",
            "Weight": "3.4 lbs (1.55 kg)",
            "Color": "Space Gray",
            "Warranty": "1-Year AppleCare Limited",
            "Discount": "5%"
        },
        "stock_qty": 50,
        "is_featured": False,
        "is_new": False,
        "rating": 4.9,
        "num_reviews": 112
    },
    {
        "name": "MacBook Pro 14-inch (M3 Pro)",
        "brand": "Apple",
        "price": 1999.00,
        "filename": "macbook-pro-14-m3-pro.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Workstation grade 14-inch pro laptop in iconic Space Black with M3 Pro chip.",
        "full_desc": "For serious developers and creative professionals. Features M3 Pro chip with 11 CPU cores, 14 GPU cores, 150GB/s memory bandwidth, and gorgeous Space Black anodized finish.",
        "specs": {
            "SKU": "APPL-MBP14-M3PRO",
            "Processor": "Apple M3 Pro (11-Core CPU / 14-Core GPU)",
            "RAM": "18GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 14-Core GPU",
            "Display Size": "14.2 inches",
            "Resolution": "3024 x 1964 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "72.4Wh",
            "Weight": "3.5 lbs (1.61 kg)",
            "Color": "Space Black",
            "Warranty": "1-Year AppleCare",
            "Discount": "0%"
        },
        "stock_qty": 45,
        "is_featured": True,
        "is_new": False,
        "rating": 4.9,
        "num_reviews": 150
    },
    {
        "name": "MacBook Pro 14-inch (M3 Max)",
        "brand": "Apple",
        "price": 3199.00,
        "filename": "macbook-pro-14-m3-max.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Monster compact workstation with M3 Max 30-core GPU and 36GB unified memory.",
        "full_desc": "Extreme power in a portable 14-inch footprint. M3 Max delivers up to 400GB/s memory bandwidth, hardware ProRes acceleration, and support for up to 4 external displays.",
        "specs": {
            "SKU": "APPL-MBP14-M3MAX",
            "Processor": "Apple M3 Max (14-Core CPU / 30-Core GPU)",
            "RAM": "36GB Unified Memory",
            "Storage": "1TB SSD",
            "GPU": "Apple 30-Core GPU",
            "Display Size": "14.2 inches",
            "Resolution": "3024 x 1964 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "72.4Wh",
            "Weight": "3.6 lbs (1.63 kg)",
            "Color": "Space Black",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "0%"
        },
        "stock_qty": 25,
        "is_featured": False,
        "is_new": False,
        "rating": 5.0,
        "num_reviews": 88
    },
    {
        "name": "MacBook Pro 16-inch (M3 Pro)",
        "brand": "Apple",
        "price": 2499.00,
        "filename": "macbook-pro-16-m3-pro.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Desktop replacing 16.2-inch Liquid Retina XDR screen laptop with M3 Pro chip.",
        "full_desc": "The ultimate professional laptop display experience. The 16.2-inch XDR screen delivers 1000 nits sustained brightness and 1,000,000:1 contrast ratio backed by M3 Pro power.",
        "specs": {
            "SKU": "APPL-MBP16-M3PRO",
            "Processor": "Apple M3 Pro (12-Core CPU / 18-Core GPU)",
            "RAM": "36GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 18-Core GPU",
            "Display Size": "16.2 inches",
            "Resolution": "3456 x 2234 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "100Wh (Up to 22 Hours)",
            "Weight": "4.7 lbs (2.14 kg)",
            "Color": "Space Black",
            "Warranty": "1-Year AppleCare",
            "Discount": "5%"
        },
        "stock_qty": 35,
        "is_featured": False,
        "is_new": False,
        "rating": 4.9,
        "num_reviews": 160
    },
    {
        "name": "MacBook Pro 16-inch (M3 Max)",
        "brand": "Apple",
        "price": 3499.00,
        "filename": "macbook-pro-16-m3-max.webp",
        "image_url": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Unrivaled flagship 16-inch workstation with M3 Max 40-core GPU and 48GB unified memory.",
        "full_desc": "Peak laptop performance. Pushes render speeds, machine learning models, and 8K video timelines to unbelievable speeds with M3 Max 40-core GPU and 48GB unified memory.",
        "specs": {
            "SKU": "APPL-MBP16-M3MAX",
            "Processor": "Apple M3 Max (16-Core CPU / 40-Core GPU)",
            "RAM": "48GB Unified Memory",
            "Storage": "1TB SSD",
            "GPU": "Apple 40-Core GPU",
            "Display Size": "16.2 inches",
            "Resolution": "3456 x 2234 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "100Wh",
            "Weight": "4.8 lbs (2.16 kg)",
            "Color": "Silver",
            "Warranty": "1-Year AppleCare Warranty",
            "Discount": "0%"
        },
        "stock_qty": 20,
        "is_featured": True,
        "is_new": False,
        "rating": 5.0,
        "num_reviews": 98
    },
    {
        "name": "MacBook Pro 14-inch (M4)",
        "brand": "Apple",
        "price": 1699.00,
        "filename": "macbook-pro-14-m4.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Next-generation 14-inch MacBook Pro powered by Apple M4 chip with Apple Intelligence.",
        "full_desc": "Built for Apple Intelligence. The all-new MacBook Pro 14 featuring Apple M4 chip delivers industry-leading single-thread performance, 12MB L2 cache, 10-core GPU, and up to 24 hours of battery efficiency.",
        "specs": {
            "SKU": "APPL-MBP14-M4",
            "Processor": "Apple M4 (10-Core CPU / 10-Core GPU)",
            "RAM": "16GB Unified Memory",
            "Storage": "512GB SSD",
            "GPU": "Apple 10-Core GPU",
            "Display Size": "14.2 inches",
            "Resolution": "3024 x 1964 Liquid Retina XDR",
            "Refresh Rate": "120Hz ProMotion",
            "Operating System": "macOS Sequoia",
            "Battery": "72.4Wh (Up to 24 Hours)",
            "Weight": "3.4 lbs (1.55 kg)",
            "Color": "Space Black",
            "Warranty": "1-Year AppleCare",
            "Discount": "0%"
        },
        "stock_qty": 50,
        "is_featured": True,
        "is_new": True,
        "rating": 5.0,
        "num_reviews": 45
    },

    # --- LENOVO (10) ---
    {
        "name": "Lenovo ThinkPad X1 Carbon Gen 12",
        "brand": "Lenovo",
        "price": 1849.00,
        "filename": "lenovo-thinkpad-x1-carbon-gen-12.webp",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Ultralight carbon-fiber business 14-inch flagship with 2.8K 120Hz OLED screen.",
        "full_desc": "The gold standard of enterprise laptops. ThinkPad X1 Carbon Gen 12 features a carbon-fiber weave chassis, TrackPoint, 2.8K OLED screen, Intel Core Ultra vPro, and computer vision user sensing.",
        "specs": {
            "SKU": "LENV-X1C-G12",
            "Processor": "Intel Core Ultra 7 155H vPro",
            "RAM": "32GB LPDDR5X",
            "Storage": "1TB PCIe Gen4 NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "57Wh",
            "Weight": "2.42 lbs (1.09 kg)",
            "Color": "Deep Black with Carbon Weave",
            "Warranty": "3-Year Premier Support",
            "Discount": "10%"
        },
        "stock_qty": 40,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 105
    },
    {
        "name": "Lenovo ThinkPad T14 Gen 5",
        "brand": "Lenovo",
        "price": 1299.00,
        "filename": "lenovo-thinkpad-t14-gen-5.webp",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Workhorse 14-inch enterprise laptop designed for repairability and durability.",
        "full_desc": "The corporate gold standard. ThinkPad T14 Gen 5 features customer replaceable unit (CRU) components co-designed with iFixit, dual SO-DIMM RAM slots, and iconic spill-resistant keyboard.",
        "specs": {
            "SKU": "LENV-T14-G5",
            "Processor": "Intel Core Ultra 5 125H",
            "RAM": "16GB DDR5 5600MHz",
            "Storage": "512GB PCIe Gen4 SSD",
            "GPU": "Intel Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 WUXGA IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "52.5Wh Swappable",
            "Weight": "2.9 lbs (1.31 kg)",
            "Color": "Thunder Black",
            "Warranty": "3-Year Depot Warranty",
            "Discount": "5%"
        },
        "stock_qty": 60,
        "is_featured": False,
        "is_new": False,
        "rating": 4.7,
        "num_reviews": 82
    },
    {
        "name": "Lenovo ThinkPad E14 Gen 6",
        "brand": "Lenovo",
        "price": 799.00,
        "filename": "lenovo-thinkpad-e14-gen-6.webp",
        "image_url": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Value-packed 14-inch business laptop with AMD Ryzen 7 and dual SSD slots.",
        "full_desc": "Essential business performance. ThinkPad E14 Gen 6 features an aluminum top cover, discrete TPM 2.0 security chip, fingerprint reader integrated on power button, and AMD Ryzen 7 power.",
        "specs": {
            "SKU": "LENV-E14-G6",
            "Processor": "AMD Ryzen 7 7735HS",
            "RAM": "16GB DDR5",
            "Storage": "512GB PCIe SSD",
            "GPU": "AMD Radeon 680M",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 WUXGA",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "57Wh",
            "Weight": "3.12 lbs (1.41 kg)",
            "Color": "Black",
            "Warranty": "1-Year Onsite Warranty",
            "Discount": "8%"
        },
        "stock_qty": 70,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 64
    },
    {
        "name": "Lenovo ThinkBook 14 Gen 7",
        "brand": "Lenovo",
        "price": 879.00,
        "filename": "lenovo-thinkbook-14-gen-7.webp",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Modern dual-tone aluminum 14-inch laptop for SMBs and freelancers.",
        "full_desc": "Sleek dual-tone anodized aluminum design. ThinkBook 14 Gen 7 delivers Core Ultra performance, Smart Power thermal control, and noise-canceling AI audio for conference calls.",
        "specs": {
            "SKU": "LENV-TB14-G7",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB DDR5",
            "Storage": "512GB NVMe M.2 SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "1920 x 1200 WUXGA IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Pro",
            "Battery": "60Wh",
            "Weight": "3.04 lbs (1.38 kg)",
            "Color": "Arctic Grey",
            "Warranty": "1-Year Depot Warranty",
            "Discount": "10%"
        },
        "stock_qty": 55,
        "is_featured": False,
        "is_new": True,
        "rating": 4.7,
        "num_reviews": 51
    },
    {
        "name": "Lenovo Yoga 7i",
        "brand": "Lenovo",
        "price": 949.00,
        "filename": "lenovo-yoga-7i.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Flexible 14-inch 2-in-1 touchscreen convertible with 2.8K OLED display.",
        "full_desc": "Versatility meets stunning visuals. Lenovo Yoga 7i features comfort-edge 360-degree aluminum design, Dolby Vision 2.8K OLED screen, digital pen support, and Quad speakers.",
        "specs": {
            "SKU": "LENV-YOGA7I-14",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5X",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED Touch",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "71Wh",
            "Weight": "3.28 lbs (1.49 kg)",
            "Color": "Tidal Teal",
            "Warranty": "1-Year Premium Care",
            "Discount": "12%"
        },
        "stock_qty": 45,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 89
    },
    {
        "name": "Lenovo Yoga 9i",
        "brand": "Lenovo",
        "price": 1699.00,
        "filename": "lenovo-yoga-9i.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Flagship 2-in-1 convertible with 4K OLED touchscreen and Bowers & Wilkins rotating soundbar.",
        "full_desc": "Luxury engineering. Lenovo Yoga 9i features a unique Bowers & Wilkins rotating soundbar hinge, 4K PureSight OLED touch panel, glass palm rest, and precision stylus included.",
        "specs": {
            "SKU": "LENV-YOGA9I-FLAG",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "32GB LPDDR5X",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "3840 x 2400 4K OLED Touch",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "75Wh",
            "Weight": "2.98 lbs (1.35 kg)",
            "Color": "Cosmic Blue",
            "Warranty": "1-Year Premium Care",
            "Discount": "5%"
        },
        "stock_qty": 25,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 73
    },
    {
        "name": "Lenovo IdeaPad Slim 5",
        "brand": "Lenovo",
        "price": 699.00,
        "filename": "lenovo-ideapad-slim-5.webp",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Sleek 16-inch laptop with AMD Ryzen 7 8845HS and metal chassis.",
        "full_desc": "Slim profile with heavyweight power. Lenovo IdeaPad Slim 5 packs an 8-core Ryzen 7 chip, military grade durability, FHD camera with privacy shutter, and rapid charge boost.",
        "specs": {
            "SKU": "LENV-IPSLIM5-16",
            "Processor": "AMD Ryzen 7 8845HS",
            "RAM": "16GB LPDDR5X",
            "Storage": "512GB PCIe SSD",
            "GPU": "AMD Radeon 780M",
            "Display Size": "16.0 inches",
            "Resolution": "1920 x 1200 WUXGA IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "56.6Wh",
            "Weight": "4.16 lbs (1.89 kg)",
            "Color": "Cloud Grey",
            "Warranty": "1-Year Mail-in Warranty",
            "Discount": "10%"
        },
        "stock_qty": 75,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 92
    },
    {
        "name": "Lenovo IdeaPad Pro 5",
        "brand": "Lenovo",
        "price": 1049.00,
        "filename": "lenovo-ideapad-pro-5.webp",
        "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Performance 16-inch laptop with 2.5K 120Hz OLED screen and RTX 4050 GPU.",
        "full_desc": "Pro creation for aspiring artists. IdeaPad Pro 5 features a factory color calibrated 2.5K OLED 120Hz display, dedicated RTX 4050 graphics, and expansion SD card slot.",
        "specs": {
            "SKU": "LENV-IPPRO5-16",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5X",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 2.5K OLED",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "84Wh",
            "Weight": "4.29 lbs (1.95 kg)",
            "Color": "Arctic Grey",
            "Warranty": "1-Year Premium Care",
            "Discount": "8%"
        },
        "stock_qty": 40,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 61
    },
    {
        "name": "Lenovo Legion Pro 5i",
        "brand": "Lenovo",
        "price": 1649.00,
        "filename": "lenovo-legion-pro-5i.webp",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Powerhouse esports gaming laptop with 240Hz WQXGA panel and RTX 4070.",
        "full_desc": "Dominate the lobby. Lenovo Legion Pro 5i features Coldfront 5.0 cooling technology with phase-change thermal compound, Legion Spectrum 4-zone RGB keyboard, and AI Engine+ optimization.",
        "specs": {
            "SKU": "LENV-LEGION-PRO5I",
            "Processor": "Intel Core i7-14700HX",
            "RAM": "32GB DDR5 5600MHz",
            "Storage": "1TB PCIe Gen4 SSD",
            "GPU": "NVIDIA GeForce RTX 4070 8GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 WQXGA",
            "Refresh Rate": "240Hz 500 nits HDR",
            "Operating System": "Windows 11 Home",
            "Battery": "80Wh Super Rapid Charge",
            "Weight": "5.5 lbs (2.5 kg)",
            "Color": "Onyx Grey",
            "Warranty": "1-Year Legion Ultimate Support",
            "Discount": "15%"
        },
        "stock_qty": 35,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 118
    },
    {
        "name": "Lenovo LOQ 15",
        "brand": "Lenovo",
        "price": 899.00,
        "filename": "lenovo-loq-15.webp",
        "image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Budget gaming powerhouse with 144Hz FHD panel and RTX 4060 GPU.",
        "full_desc": "Enter the world of PC gaming. Lenovo LOQ 15 packs an MUX Switch with Advanced Optimus, NVIDIA RTX 4060 graphics, and signature rear I/O port design for clean desk setups.",
        "specs": {
            "SKU": "LENV-LOQ15-GAM",
            "Processor": "AMD Ryzen 7 7435HS",
            "RAM": "16GB DDR5 4800MHz",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4060 8GB",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD G-Sync",
            "Refresh Rate": "144Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "60Wh",
            "Weight": "5.28 lbs (2.39 kg)",
            "Color": "Luna Grey",
            "Warranty": "1-Year Limited Warranty",
            "Discount": "10%"
        },
        "stock_qty": 50,
        "is_featured": False,
        "is_new": False,
        "rating": 4.7,
        "num_reviews": 84
    },

    # --- ACER (10) ---
    {
        "name": "Acer Aspire 3",
        "brand": "Acer",
        "price": 449.00,
        "filename": "acer-aspire-3.webp",
        "image_url": "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Essential budget 15.6-inch laptop with AMD Ryzen 5 processor and 512GB SSD.",
        "full_desc": "Practical everyday computing. Acer Aspire 3 features an anti-glare Full HD screen, PurifiedVoice AI noise reduction, and thermal performance improved by 78% over previous generation.",
        "specs": {
            "SKU": "ACER-ASP3-15",
            "Processor": "AMD Ryzen 5 7520U",
            "RAM": "8GB LPDDR5",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "AMD Radeon 610M",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD ComfyView",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "40Wh",
            "Weight": "3.92 lbs (1.78 kg)",
            "Color": "Pure Silver",
            "Warranty": "1-Year Acer International",
            "Discount": "10%"
        },
        "stock_qty": 90,
        "is_featured": False,
        "is_new": False,
        "rating": 4.3,
        "num_reviews": 110
    },
    {
        "name": "Acer Aspire 5",
        "brand": "Acer",
        "price": 649.00,
        "filename": "acer-aspire-5.webp",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Popular 15.6-inch home office laptop with 13th Gen Intel i7 processor.",
        "full_desc": "Maximize your everyday productivity. Acer Aspire 5 features an aluminum top cover, Thunderbolt 4 connectivity, Wi-Fi 6E, and Acer TNR solution for enhanced webcam video in low light.",
        "specs": {
            "SKU": "ACER-ASP5-15",
            "Processor": "Intel Core i7-1355U",
            "RAM": "16GB LPDDR5",
            "Storage": "512GB PCIe NVMe SSD",
            "GPU": "Intel Iris Xe Graphics",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "60Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "50Wh",
            "Weight": "3.88 lbs (1.76 kg)",
            "Color": "Steel Grey",
            "Warranty": "1-Year Limited Warranty",
            "Discount": "8%"
        },
        "stock_qty": 65,
        "is_featured": False,
        "is_new": False,
        "rating": 4.5,
        "num_reviews": 95
    },
    {
        "name": "Acer Aspire 7",
        "brand": "Acer",
        "price": 799.00,
        "filename": "acer-aspire-7.webp",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Understated 15.6-inch laptop with discrete RTX 3050 graphics and 144Hz screen.",
        "full_desc": "Subtle design with serious muscle. Acer Aspire 7 conceals discrete NVIDIA RTX 3050 graphics inside a sleek charcoal chassis with dual fans and multiple cooling modes.",
        "specs": {
            "SKU": "ACER-ASP7-15",
            "Processor": "Intel Core i5-12450H",
            "RAM": "16GB DDR4",
            "Storage": "512GB PCIe SSD",
            "GPU": "NVIDIA GeForce RTX 3050 4GB",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "144Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "50Wh",
            "Weight": "4.74 lbs (2.15 kg)",
            "Color": "Charcoal Black",
            "Warranty": "1-Year Acer Warranty",
            "Discount": "12%"
        },
        "stock_qty": 45,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 58
    },
    {
        "name": "Acer Swift Go 14",
        "brand": "Acer",
        "price": 899.00,
        "filename": "acer-swift-go-14.webp",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Ultra-portable 14-inch 2.8K OLED laptop with Intel Core Ultra 7 processor.",
        "full_desc": "Vivid OLED portability. Acer Swift Go 14 features a gorgeous 2.8K OLED screen with 100% DCI-P3 color gamut, 1440p QHD webcam, and ultra-thin 14.9mm aluminum chassis.",
        "specs": {
            "SKU": "ACER-SWIFT-GO14",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16GB LPDDR5X",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "Intel Arc Graphics",
            "Display Size": "14.0 inches",
            "Resolution": "2880 x 1800 2.8K OLED",
            "Refresh Rate": "90Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "65Wh",
            "Weight": "2.91 lbs (1.32 kg)",
            "Color": "Sunshiny Gold",
            "Warranty": "1-Year Acer Premium Warranty",
            "Discount": "10%"
        },
        "stock_qty": 50,
        "is_featured": True,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 79
    },
    {
        "name": "Acer Swift X 14",
        "brand": "Acer",
        "price": 1299.00,
        "filename": "acer-swift-x-14.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Compact creator laptop with 2.8K 120Hz OLED screen and RTX 4050 Studio drivers.",
        "full_desc": "Mobile Studio for digital artists. Acer Swift X 14 packs NVIDIA Studio validated RTX 4050 graphics, Calman verified 2.8K OLED panel, and ring fan cooling system.",
        "specs": {
            "SKU": "ACER-SWIFT-X14",
            "Processor": "Intel Core i7-13700H",
            "RAM": "16GB LPDDR5",
            "Storage": "1TB PCIe Gen4 SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "14.5 inches",
            "Resolution": "2880 x 1800 2.8K OLED",
            "Refresh Rate": "120Hz Calman Verified",
            "Operating System": "Windows 11 Home",
            "Battery": "76Wh",
            "Weight": "3.42 lbs (1.55 kg)",
            "Color": "Steel Grey",
            "Warranty": "1-Year Limited Warranty",
            "Discount": "5%"
        },
        "stock_qty": 30,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 52
    },
    {
        "name": "Acer Swift Edge 16",
        "brand": "Acer",
        "price": 1199.00,
        "filename": "acer-swift-edge-16.webp",
        "image_url": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "World's lightest 16-inch 3.2K OLED laptop weighing under 2.7 lbs.",
        "full_desc": "Featherweight 16-inch marvel. Acer Swift Edge 16 uses magnesium-aluminum alloy to achieve an impossibly light 2.71 lbs frame while boasting a stunning 3.2K 120Hz OLED display.",
        "specs": {
            "SKU": "ACER-SWIFT-EDGE16",
            "Processor": "AMD Ryzen 7 7840U",
            "RAM": "16GB LPDDR5",
            "Storage": "1TB PCIe Gen4 SSD",
            "GPU": "AMD Radeon 780M",
            "Display Size": "16.0 inches",
            "Resolution": "3200 x 2000 3.2K OLED",
            "Refresh Rate": "120Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "54Wh",
            "Weight": "2.71 lbs (1.23 kg)",
            "Color": "Olivine Black",
            "Warranty": "1-Year Warranty",
            "Discount": "15%"
        },
        "stock_qty": 35,
        "is_featured": False,
        "is_new": False,
        "rating": 4.7,
        "num_reviews": 63
    },
    {
        "name": "Acer Nitro V 15",
        "brand": "Acer",
        "price": 749.00,
        "filename": "acer-nitro-v-15.webp",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "High-value gaming laptop with 144Hz FHD display and RTX 4050 GPU.",
        "full_desc": "Stepping stone to gaming victory. Acer Nitro V 15 delivers smooth 1080p gameplay with Intel 13th Gen H-series processors, dual intake fans, and NitroSense control software.",
        "specs": {
            "SKU": "ACER-NITRO-V15",
            "Processor": "Intel Core i5-13420H",
            "RAM": "16GB DDR5 5200MHz",
            "Storage": "512GB PCIe Gen4 SSD",
            "GPU": "NVIDIA GeForce RTX 4050 6GB",
            "Display Size": "15.6 inches",
            "Resolution": "1920 x 1080 FHD IPS",
            "Refresh Rate": "144Hz",
            "Operating System": "Windows 11 Home",
            "Battery": "57Wh",
            "Weight": "4.66 lbs (2.11 kg)",
            "Color": "Obsidian Black",
            "Warranty": "1-Year Acer Gaming Warranty",
            "Discount": "10%"
        },
        "stock_qty": 70,
        "is_featured": False,
        "is_new": False,
        "rating": 4.6,
        "num_reviews": 125
    },
    {
        "name": "Acer Nitro 16",
        "brand": "Acer",
        "price": 1149.00,
        "filename": "acer-nitro-16.webp",
        "image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Powerful 16-inch gaming laptop with 165Hz WQXGA panel and RTX 4060 GPU.",
        "full_desc": "Full-throttle gaming performance. Acer Nitro 16 pairs AMD Ryzen 7 7840HS with liquid metal thermal grease on CPU, 4-zone RGB keyboard, and 165Hz 100% sRGB display.",
        "specs": {
            "SKU": "ACER-NITRO-16",
            "Processor": "AMD Ryzen 7 7840HS",
            "RAM": "16GB DDR5 5600MHz",
            "Storage": "1TB PCIe NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4060 8GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 WQXGA IPS",
            "Refresh Rate": "165Hz G-Sync",
            "Operating System": "Windows 11 Home",
            "Battery": "90Wh",
            "Weight": "5.95 lbs (2.7 kg)",
            "Color": "Obsidian Black",
            "Warranty": "1-Year Limited Warranty",
            "Discount": "12%"
        },
        "stock_qty": 40,
        "is_featured": False,
        "is_new": True,
        "rating": 4.8,
        "num_reviews": 84
    },
    {
        "name": "Acer Predator Helios Neo 16",
        "brand": "Acer",
        "price": 1399.00,
        "filename": "acer-predator-helios-neo-16.webp",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Esports grade 16-inch gaming rig with 240Hz display and RTX 4060 graphics.",
        "full_desc": "Decode the matrix. Predator Helios Neo 16 features laser-etched cipher codes on its aluminum cover, 5th Gen AeroBlade 3D fan technology, liquid metal cooling, and 240Hz screen.",
        "specs": {
            "SKU": "ACER-HELIOS-NEO16",
            "Processor": "Intel Core i7-14700HX",
            "RAM": "16GB DDR5 5600MHz",
            "Storage": "1TB PCIe Gen4 SSD",
            "GPU": "NVIDIA GeForce RTX 4060 8GB",
            "Display Size": "16.0 inches",
            "Resolution": "2560 x 1600 WQXGA",
            "Refresh Rate": "240Hz 3ms",
            "Operating System": "Windows 11 Home",
            "Battery": "90Wh",
            "Weight": "5.73 lbs (2.6 kg)",
            "Color": "Abyssal Black",
            "Warranty": "1-Year Predator VIP Support",
            "Discount": "10%"
        },
        "stock_qty": 35,
        "is_featured": True,
        "is_new": True,
        "rating": 4.9,
        "num_reviews": 96
    },
    {
        "name": "Acer Predator Helios 18",
        "brand": "Acer",
        "price": 2799.00,
        "filename": "acer-predator-helios-18.webp",
        "image_url": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
        "short_desc": "Extreme 18-inch Mini-LED 250Hz gaming beast with RTX 4080 and i9-14900HX.",
        "full_desc": "Absolute gaming titan. Predator Helios 18 boasts an 18-inch WQXGA Mini-LED screen with 1000+ local dimming zones, 250Hz refresh rate, MagKey 3.0 swappable keycaps, and RTX 4080 12GB graphics.",
        "specs": {
            "SKU": "ACER-HELIOS-18",
            "Processor": "Intel Core i9-14900HX",
            "RAM": "32GB DDR5 5600MHz",
            "Storage": "2TB PCIe Gen4 NVMe SSD",
            "GPU": "NVIDIA GeForce RTX 4080 12GB",
            "Display Size": "18.0 inches",
            "Resolution": "2560 x 1600 WQXGA Mini-LED",
            "Refresh Rate": "250Hz 1000 nits",
            "Operating System": "Windows 11 Home",
            "Battery": "90Wh",
            "Weight": "7.16 lbs (3.25 kg)",
            "Color": "Abyssal Black",
            "Warranty": "1-Year Predator VIP Support",
            "Discount": "15%"
        },
        "stock_qty": 15,
        "is_featured": True,
        "is_new": True,
        "rating": 5.0,
        "num_reviews": 68
    }
]

# Ensure Category 'Laptops' exists
laptop_cat, _ = Category.objects.get_or_create(
    slug='laptops',
    defaults={
        'name': 'Laptops',
        'icon': 'Laptop',
        'description': 'Authentic high-performance laptops from Dell, HP, Apple, Lenovo, and Acer'
    }
)
if laptop_cat.name != 'Laptops':
    laptop_cat.name = 'Laptops'
    laptop_cat.save()

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

print("Downloading product photography and populating database...")

for i, laptop in enumerate(LAPTOPS, start=1):
    file_path = os.path.join(DEST_DIR, laptop["filename"])
    
    # Download image if not present or corrupt
    if not os.path.exists(file_path):
        try:
            print(f"[{i}/50] Downloading image for {laptop['name']}...")
            resp = requests.get(laptop["image_url"], headers=headers, timeout=10)
            if resp.status_code == 200:
                img = Image.open(io.BytesIO(resp.content)).convert('RGB')
                # Resize nicely
                img.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
                img.save(file_path, 'WEBP', quality=90)
                print(f"Saved {laptop['filename']}")
            else:
                print(f"Failed HTTP {resp.status_code} for {laptop['name']}")
        except Exception as e:
            print(f"Error downloading {laptop['name']}: {e}")
    else:
        print(f"[{i}/50] Image already exists: {laptop['filename']}")

    # Relative web path for database reference
    web_image_url = f"/images/products/laptops/{laptop['filename']}"

    # Update or create product in DB
    prod, created = Product.objects.update_or_create(
        name=laptop["name"],
        category=laptop_cat,
        defaults={
            'brand': laptop["brand"],
            'price': laptop["price"],
            'description': laptop["full_desc"],
            'specs': laptop["specs"],
            'stock_qty': laptop["stock_qty"],
            'image_url': web_image_url,
            'is_featured': laptop["is_featured"],
            'is_new': laptop["is_new"],
            'rating': laptop["rating"],
            'num_reviews': laptop["num_reviews"],
        }
    )

    action = "Created" if created else "Updated"
    print(f"DB {action}: {prod.name} (${prod.price})")

print("\nSuccessfully populated 50 laptop products into the database and saved webp images!")
