from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from store.models import Category, Product, Order, OrderItem, CartItem, Review, Wishlist

User = get_user_model()

class Command(BaseCommand):
    help = 'Seeds the database with realistic dummy electronics data matching the NEXUS futuristic UI'

    def handle(self, *args, **options):
        self.stdout.write(self.style.WARNING('Seeding database with 30 Laptop items + full store catalog...'))

        # Create Admin User
        admin, created = User.objects.get_or_create(
            username='admin',
            defaults={
                'email': 'admin@nexus.io',
                'name': 'Nexus Admin',
                'role': 'admin',
                'is_staff': True,
                'is_superuser': True,
                'shipping_address': 'Nexus HQ 1 Quantum Way',
                'city': 'San Jose',
                'postal_code': '95134',
                'country': 'United States',
                'avatar_url': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200',
            }
        )
        if created:
            admin.set_password('admin123')
            admin.save()
            self.stdout.write(self.style.SUCCESS('Admin user created: admin / admin123'))

        # Create Customer User
        customer, created = User.objects.get_or_create(
            username='john_doe',
            defaults={
                'email': 'john@example.com',
                'name': 'John Doe',
                'role': 'customer',
                'phone_number': '+1 (555) 234-5678',
                'shipping_address': '100 Silicon Valley Way, Suite 400',
                'city': 'San Jose',
                'postal_code': '95134',
                'country': 'United States',
                'avatar_url': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200',
            }
        )
        if created:
            customer.set_password('password123')
            customer.save()
            self.stdout.write(self.style.SUCCESS('Customer user created: john_doe / password123'))

        # Create Categories
        categories_data = [
            {'name': 'Laptops', 'slug': 'laptops', 'icon': 'Laptop', 'description': 'Futuristic workstations & quantum ultrabooks'},
            {'name': 'Phones', 'slug': 'phones', 'icon': 'Smartphone', 'description': 'Flagship foldable & holographic smartphone hardware'},
            {'name': 'Tablets', 'slug': 'tablets', 'icon': 'Tablet', 'description': 'Ultra-thin OLED digital art canvases'},
            {'name': 'Audio', 'slug': 'audio', 'icon': 'Headphones', 'description': 'Spatial lossy acoustic foam and transparent ANC buds'},
            {'name': 'Accessories', 'slug': 'accessories', 'icon': 'Watch', 'description': 'Sapphire glass wearables & Thunderbolt glass docks'},
        ]

        cat_objs = {}
        for cat in categories_data:
            obj, _ = Category.objects.get_or_create(
                slug=cat['slug'],
                defaults={'name': cat['name'], 'icon': cat['icon'], 'description': cat['description']}
            )
            cat_objs[cat['slug']] = obj

        # Products Seed Data
        products_data = [
            # --- 30 LAPTOPS ---
            {
                'name': 'NexusBook Pro X16',
                'category': cat_objs['laptops'],
                'price': 2499.00,
                'brand': 'NEXUS',
                'description': 'The ultimate futuristic workstation with liquid glass trackpad, Quantum OLED display, and M3 Max architecture.',
                'specs': {'chip': 'Quantum M3 Max', 'ram': '36GB Unified', 'storage': '1TB NVMe Gen4', 'display': '16.2" 120Hz Mini-LED'},
                'stock_qty': 15,
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Aura Air 14 Glass',
                'category': cat_objs['laptops'],
                'price': 1399.00,
                'brand': 'AURA',
                'description': 'Ultra-thin aerospace aluminum body with silent fanless cooling and all-day 22-hour battery life.',
                'specs': {'chip': 'Aura Silicon 2', 'ram': '16GB RAM', 'storage': '512GB SSD', 'weight': '1.24 kg'},
                'stock_qty': 25,
                'image_url': 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': False,
                'rating': 4.8,
            },
            {
                'name': 'Cyberware Blade 15',
                'category': cat_objs['laptops'],
                'price': 2899.00,
                'brand': 'CYBERWARE',
                'description': 'Next-gen raytracing gaming titan with RTX 4090 Mobile, per-key RGB glass keyboard, and vapor chamber cooling.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4090 16GB', 'ram': '32GB DDR5', 'display': '240Hz QHD+'},
                'stock_qty': 8,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Apple MacBook Pro 16 M3 Max',
                'category': cat_objs['laptops'],
                'price': 3499.00,
                'brand': 'Apple',
                'description': 'Space Black Liquid Retina XDR display workstation powered by 16-core CPU M3 Max and 40-core GPU.',
                'specs': {'chip': 'Apple M3 Max', 'ram': '48GB Unified', 'storage': '1TB SSD', 'display': '16.2" Liquid Retina XDR'},
                'stock_qty': 12,
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 5.0,
            },
            {
                'name': 'Apple MacBook Air 15 M3',
                'category': cat_objs['laptops'],
                'price': 1299.00,
                'brand': 'Apple',
                'description': 'Impossibly thin 15-inch aluminum design with fanless M3 efficiency and MagSafe 3 charging.',
                'specs': {'chip': 'Apple M3 8-Core', 'ram': '16GB Unified', 'storage': '512GB SSD', 'display': '15.3" Liquid Retina'},
                'stock_qty': 30,
                'image_url': 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Apple MacBook Pro 14 M3 Pro',
                'category': cat_objs['laptops'],
                'price': 1999.00,
                'brand': 'Apple',
                'description': 'Compact power titan for creative professionals with 18-hour battery and 120Hz ProMotion display.',
                'specs': {'chip': 'Apple M3 Pro', 'ram': '18GB Unified', 'storage': '512GB SSD', 'display': '14.2" ProMotion 120Hz'},
                'stock_qty': 20,
                'image_url': 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.8,
            },
            {
                'name': 'Dell XPS 16 OLED Titanium',
                'category': cat_objs['laptops'],
                'price': 2399.00,
                'brand': 'Dell',
                'description': 'Seamless glass palm rest with capacitive touch function row, 4K OLED touch panel, and RTX 4070 Graphics.',
                'specs': {'chip': 'Intel Core Ultra 9', 'gpu': 'RTX 4070 8GB', 'ram': '32GB LPDDR5X', 'display': '16.3" 4K OLED Touch'},
                'stock_qty': 10,
                'image_url': 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.7,
            },
            {
                'name': 'Dell Alienware m18 R2 Gaming',
                'category': cat_objs['laptops'],
                'price': 3199.00,
                'brand': 'Dell',
                'description': '18-inch desktop replacement beast featuring Element 31 thermal liquid metal and Cherry MX mechanical keycaps.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4090 16GB', 'ram': '64GB DDR5', 'display': '18.0" 480Hz FHD+'},
                'stock_qty': 6,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Dell XPS 14 Ultra Compact',
                'category': cat_objs['laptops'],
                'price': 1699.00,
                'brand': 'Dell',
                'description': 'CNC machined aluminum chassis with Gorilla Glass 3 borderless display and AI-accelerated NPU processor.',
                'specs': {'chip': 'Intel Core Ultra 7', 'gpu': 'RTX 4050 6GB', 'ram': '16GB LPDDR5X', 'display': '14.5" 3.2K OLED'},
                'stock_qty': 18,
                'image_url': 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.6,
            },
            {
                'name': 'Dell Latitude 9450 2-in-1 Glass',
                'category': cat_objs['laptops'],
                'price': 2099.00,
                'brand': 'Dell',
                'description': 'Enterprise convertible 2-in-1 featuring haptic collaboration touchpad and zero-lattice zero-energy keyboard.',
                'specs': {'chip': 'Intel Core Ultra 7 vPro', 'ram': '32GB LPDDR5x', 'storage': '1TB SSD', 'display': '14.0" QHD+ Touch 360°'},
                'stock_qty': 14,
                'image_url': 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.7,
            },
            {
                'name': 'HP Spectre x360 16 OLED',
                'category': cat_objs['laptops'],
                'price': 1899.00,
                'brand': 'HP',
                'description': 'Gem-cut 360-degree convertible with 9MP AI auto-frame webcam and quad Bang & Olufsen tuned acoustic speakers.',
                'specs': {'chip': 'Intel Core Ultra 7 155H', 'ram': '32GB LPDDR5', 'storage': '2TB NVMe', 'display': '16.0" 2.8K OLED Touch'},
                'stock_qty': 15,
                'image_url': 'https://images.unsplash.com/photo-1544731612-de7f96afe55f?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.8,
            },
            {
                'name': 'HP OMEN Transcend 14',
                'category': cat_objs['laptops'],
                'price': 1599.00,
                'brand': 'HP',
                'description': 'The world\'s lightest 14-inch gaming laptop with IMAX Enhanced OLED screen and HyperX wireless headset pairing.',
                'specs': {'chip': 'Intel Core Ultra 9 185H', 'gpu': 'RTX 4070 8GB', 'ram': '32GB LPDDR5X', 'display': '14.0" 2.8K 120Hz OLED'},
                'stock_qty': 22,
                'image_url': 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.7,
            },
            {
                'name': 'HP Dragonfly Pro Studio',
                'category': cat_objs['laptops'],
                'price': 1749.00,
                'brand': 'HP',
                'description': 'Ultra-premium business laptop with 400-nit high brightness display, 24/7 concierge support integration, and sustainable recycled alloys.',
                'specs': {'chip': 'AMD Ryzen 7 PRO 7736U', 'ram': '32GB LPDDR5', 'storage': '1TB SSD', 'display': '14.0" 120Hz Touch'},
                'stock_qty': 11,
                'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.6,
            },
            {
                'name': 'HP ZBook Studio G10 Workstation',
                'category': cat_objs['laptops'],
                'price': 2699.00,
                'brand': 'HP',
                'description': 'Heavyweight mobile workstation engineered for 8K rendering, CAD modelling, and ISV software certification.',
                'specs': {'chip': 'Intel Core i9-13900H', 'gpu': 'NVIDIA RTX 4000 Ada', 'ram': '64GB DDR5', 'display': '16.0" DreamColor 120Hz'},
                'stock_qty': 7,
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.9,
            },
            {
                'name': 'Lenovo ThinkPad X1 Carbon Gen 12',
                'category': cat_objs['laptops'],
                'price': 1949.00,
                'brand': 'Lenovo',
                'description': 'Legendary carbon-fiber business ultrabook featuring TrackPoint glass touchpad, 8K webcam bar, and MIL-STD 810H durability.',
                'specs': {'chip': 'Intel Core Ultra 7 165U', 'ram': '32GB LPDDR5X', 'storage': '1TB Gen4 SSD', 'display': '14.0" 2.8K OLED 120Hz'},
                'stock_qty': 20,
                'image_url': 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Lenovo Legion Pro 7i Gen 9',
                'category': cat_objs['laptops'],
                'price': 2599.00,
                'brand': 'Lenovo',
                'description': 'AI-tuned gaming powerhouse with LA2-Q AI chip, Coldfront 5.0 vapor chamber, and TrueStrike RGB keyboard.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4080 12GB', 'ram': '32GB DDR5', 'display': '16.0" 240Hz WQXGA'},
                'stock_qty': 12,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.8,
            },
            {
                'name': 'Lenovo Yoga Book 9i Dual Screen',
                'category': cat_objs['laptops'],
                'price': 1999.00,
                'brand': 'Lenovo',
                'description': 'Revolutionary dual 13.3-inch OLED touchscreen laptop with origami stand, bluetooth detachable keyboard, and stylus pen.',
                'specs': {'chip': 'Intel Core Ultra 7', 'ram': '16GB LPDDR5X', 'storage': '1TB SSD', 'display': 'Dual 13.3" 2.8K OLED Touch'},
                'stock_qty': 9,
                'image_url': 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': False,
                'rating': 4.7,
            },
            {
                'name': 'Lenovo Slim 7i Aura Edition',
                'category': cat_objs['laptops'],
                'price': 1279.00,
                'brand': 'Lenovo',
                'description': 'Sleek dark lunar gray metal chassis with smart share tap-to-transfer tech and ultra-low power consumption.',
                'specs': {'chip': 'Intel Core Ultra 7 258V', 'ram': '32GB LPDDR5X', 'storage': '1TB SSD', 'display': '15.3" 2.8K 120Hz'},
                'stock_qty': 25,
                'image_url': 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.6,
            },
            {
                'name': 'ASUS ROG Zephyrus G16 OLED',
                'category': cat_objs['laptops'],
                'price': 2299.00,
                'brand': 'ASUS',
                'description': 'Slash lighting CNC aluminum lid with ROG Nebula OLED display, Tri-Fan thermal technology, and 2.5K 240Hz response time.',
                'specs': {'chip': 'Intel Core Ultra 9 185H', 'gpu': 'RTX 4070 8GB', 'ram': '32GB LPDDR5X', 'display': '16.0" 2.5K 240Hz OLED'},
                'stock_qty': 16,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'ASUS Zenbook Duo Dual 14" OLED',
                'category': cat_objs['laptops'],
                'price': 1499.00,
                'brand': 'ASUS',
                'description': 'Dual 14-inch 3K 120Hz OLED touchscreens with built-in kickstand and full detachable magnetic keyboard.',
                'specs': {'chip': 'Intel Core Ultra 9', 'ram': '32GB LPDDR5X', 'storage': '1TB Gen4', 'display': 'Dual 14.0" 3K 120Hz OLED'},
                'stock_qty': 14,
                'image_url': 'https://images.unsplash.com/photo-1544731612-de7f96afe55f?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': False,
                'rating': 4.8,
            },
            {
                'name': 'ASUS ROG Strix SCAR 18 Titan',
                'category': cat_objs['laptops'],
                'price': 3699.00,
                'brand': 'ASUS',
                'description': 'The pinnacle of desktop replacement gaming with ROG Armoury Crate custom overclocking and 2000+ zone Mini-LED panel.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4090 16GB', 'ram': '64GB DDR5', 'display': '18.0" 2.5K 240Hz Mini-LED'},
                'stock_qty': 5,
                'image_url': 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 5.0,
            },
            {
                'name': 'ASUS ProArt P16 Creator Studio',
                'category': cat_objs['laptops'],
                'price': 2499.00,
                'brand': 'ASUS',
                'description': 'NVIDIA Studio certified laptop equipped with ASUS DialPad controller for Adobe Creative Cloud precision.',
                'specs': {'chip': 'AMD Ryzen AI 9 HX 370', 'gpu': 'RTX 4070 8GB', 'ram': '64GB LPDDR5X', 'display': '16.0" 4K OLED Touch'},
                'stock_qty': 11,
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.9,
            },
            {
                'name': 'MSI Titan 18 HX Monster',
                'category': cat_objs['laptops'],
                'price': 4499.00,
                'brand': 'MSI',
                'description': 'The most powerful laptop ever created by MSI, with haptic RGB glass touchpad, 4 SSD slots, and Cherry mechanical switches.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4090 16GB', 'ram': '128GB DDR5', 'display': '18.0" 4K 120Hz Mini-LED'},
                'stock_qty': 4,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'MSI Stealth 16 AI Studio Glass',
                'category': cat_objs['laptops'],
                'price': 1999.00,
                'brand': 'MSI',
                'description': 'Ultra-thin magnesium-aluminum alloy chassis with Dynaudio 6-speaker system and 99.9Whr maximum flight legal battery.',
                'specs': {'chip': 'Intel Core Ultra 9 185H', 'gpu': 'RTX 4070 8GB', 'ram': '32GB DDR5', 'display': '16.0" 240Hz QHD+ OLED'},
                'stock_qty': 15,
                'image_url': 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.7,
            },
            {
                'name': 'Razer Blade 16 Dual-Spec Mini-LED',
                'category': cat_objs['laptops'],
                'price': 3799.00,
                'brand': 'Razer',
                'description': 'World\'s first dual-mode Mini-LED display capable of switching natively between 4K 120Hz and FHD+ 240Hz.',
                'specs': {'chip': 'Intel i9-14900HX', 'gpu': 'RTX 4090 16GB', 'ram': '32GB DDR5', 'display': '16.0" Dual-Mode Mini-LED'},
                'stock_qty': 8,
                'image_url': 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Razer Blade 14 Mercury White',
                'category': cat_objs['laptops'],
                'price': 2199.00,
                'brand': 'Razer',
                'description': 'Compact 14-inch CNC anodized white aluminum chassis with ultra-responsive 240Hz QHD+ screen.',
                'specs': {'chip': 'AMD Ryzen 9 8945HS', 'gpu': 'RTX 4070 8GB', 'ram': '32GB DDR5', 'display': '14.0" 240Hz QHD+'},
                'stock_qty': 12,
                'image_url': 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.8,
            },
            {
                'name': 'Acer Predator Triton 17 X',
                'category': cat_objs['laptops'],
                'price': 2999.00,
                'brand': 'Acer',
                'description': 'CNC unibody gaming titan with 5th Gen AeroBlade 3D metal fans, liquid metal thermal paste, and 250Hz Mini-LED.',
                'specs': {'chip': 'Intel i9-13900HX', 'gpu': 'RTX 4090 16GB', 'ram': '64GB DDR5', 'display': '17.0" 250Hz WQXGA Mini-LED'},
                'stock_qty': 7,
                'image_url': 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.7,
            },
            {
                'name': 'Acer Swift 14 AI OLED Ultrabook',
                'category': cat_objs['laptops'],
                'price': 1199.00,
                'brand': 'Acer',
                'description': 'Copilot+ PC featuring Qualcomm Snapdragon X Elite neural processing and iridescent multi-color LED trackpad indicator.',
                'specs': {'chip': 'Snapdragon X Elite 12-Core', 'ram': '16GB LPDDR5X', 'storage': '1TB SSD', 'display': '14.5" 2.8K 120Hz OLED'},
                'stock_qty': 28,
                'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.6,
            },
            {
                'name': 'NexusBook Ultra 14 Touch',
                'category': cat_objs['laptops'],
                'price': 1599.00,
                'brand': 'NEXUS',
                'description': 'Quantum holographic glass bezel with sub-millisecond capacitive response and biometric iris scanner.',
                'specs': {'chip': 'Quantum M2 Ultra', 'ram': '32GB Unified', 'storage': '1TB SSD', 'display': '14.0" 3K Quantum Touch'},
                'stock_qty': 18,
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Alienware x16 R2 Slim Gaming',
                'category': cat_objs['laptops'],
                'price': 2799.00,
                'brand': 'Dell',
                'description': 'Ultra-thin 18.5mm Lunar Light chassis with 100-micro LED rear stadium lighting strip and Cryo-Tech cooling.',
                'specs': {'chip': 'Intel Core Ultra 9 185H', 'gpu': 'RTX 4080 12GB', 'ram': '32GB LPDDR5X', 'display': '16.0" 240Hz QHD+'},
                'stock_qty': 9,
                'image_url': 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.8,
            },

            # --- PHONES ---
            {
                'name': 'Nexus Phone 15 Ultra',
                'category': cat_objs['phones'],
                'price': 1199.00,
                'brand': 'NEXUS',
                'description': 'Titanium alloy frame with quad-sensor 200MP periscope zoom and holographic notification glyph interface.',
                'specs': {'camera': '200MP Quad Cam', 'battery': '5500mAh 100W', 'display': '6.8" 144Hz AMOLED', 'chip': 'Snapdragon 8 Gen 3'},
                'stock_qty': 30,
                'image_url': 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Aura Fold Z Neo',
                'category': cat_objs['phones'],
                'price': 1799.00,
                'brand': 'AURA',
                'description': 'Zero-gap dual foldable glass OLED panel that transforms from a sleek phone into an 8-inch high-definition canvas.',
                'specs': {'display': '8.0" Foldable Dynamic OLED', 'chip': 'Aura Bionic 5G', 'ram': '12GB RAM', 'camera': '50MP Triple OIS'},
                'stock_qty': 12,
                'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.7,
            },
            {
                'name': 'Vortex Phone One',
                'category': cat_objs['phones'],
                'price': 799.00,
                'brand': 'VORTEX',
                'description': 'Clean minimalist transparent glass back panel with ambient LED pulse indicators and stock Android OS.',
                'specs': {'chip': 'MediaTek Dimensity 9200+', 'camera': '50MP Dual Sony', 'battery': '5000mAh 67W', 'display': '6.67" 120Hz OLED'},
                'stock_qty': 20,
                'image_url': 'https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.6,
            },

            # --- TABLETS ---
            {
                'name': 'NexusPad Pro 13',
                'category': cat_objs['tablets'],
                'price': 1099.00,
                'brand': 'NEXUS',
                'description': 'Tandem OLED display with nano-texture glass option and active magnetic stylus support for digital artist professionals.',
                'specs': {'display': '13.0" Ultra Retina OLED', 'chip': 'Quantum M4', 'storage': '256GB SSD', 'pen': 'Stylus Pro Included'},
                'stock_qty': 18,
                'image_url': 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': False,
                'rating': 4.9,
            },
            {
                'name': 'Aura Tab Lite 11',
                'category': cat_objs['tablets'],
                'price': 499.00,
                'brand': 'AURA',
                'description': 'Lightweight metal unibody media tablet with quad Dolby Atmos speakers and eye-care TÜV certified screen.',
                'specs': {'display': '11.0" 2K 120Hz', 'chip': 'Octa-Core 2.8GHz', 'audio': 'Quad Dolby Atmos', 'battery': '8000mAh'},
                'stock_qty': 40,
                'image_url': 'https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': False,
                'rating': 4.5,
            },

            # --- AUDIO ---
            {
                'name': 'Nexus SoundPods Max',
                'category': cat_objs['audio'],
                'price': 449.00,
                'brand': 'NEXUS',
                'description': 'Over-ear spatial audio headphones with acoustic memory foam cushions and active hybrid ANC up to -45dB.',
                'specs': {'anc': 'Hybrid Active Noise Cancelling', 'battery': '45h Playtime', 'drivers': '40mm Titanium', 'codec': 'LDAC Lossless'},
                'stock_qty': 35,
                'image_url': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': True,
                'rating': 4.9,
            },
            {
                'name': 'Aura Buds Pulse',
                'category': cat_objs['audio'],
                'price': 199.00,
                'brand': 'AURA',
                'description': 'Transparent glass charging case with stem touch controls, spatial audio tracking, and IPX5 water resistance.',
                'specs': {'anc': 'Adaptive ANC 2.0', 'battery': '8h + 24h Case', 'mic': 'Triple AI Beamforming', 'waterproof': 'IPX5'},
                'stock_qty': 50,
                'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.7,
            },

            # --- ACCESSORIES ---
            {
                'name': 'Nexus Watch Ultra Glass',
                'category': cat_objs['accessories'],
                'price': 699.00,
                'brand': 'NEXUS',
                'description': 'Sapphire glass screen with aerospace titanium case, dual-frequency GPS, and 100m water resistance rating.',
                'specs': {'display': '2.0" Sapphire OLED 3000 nits', 'battery': '72h Extreme Mode', 'sensors': 'ECG, SpO2, Temp', 'water': '100m WR'},
                'stock_qty': 22,
                'image_url': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1000&auto=format&fit=crop',
                'is_featured': True,
                'is_new': False,
                'rating': 4.8,
            },
            {
                'name': 'CyberDock 12-in-1 Glass Station',
                'category': cat_objs['accessories'],
                'price': 229.00,
                'brand': 'CYBERWARE',
                'description': 'RGB illuminated transparent glass Thunderbolt 4 dock with dual 4K 120Hz output and 100W PD charging.',
                'specs': {'ports': '12 Ports Dual HDMI/DP', 'speed': '40Gbps Thunderbolt 4', 'power': '100W Pass-Through', 'rgb': 'Custom RGB Glow'},
                'stock_qty': 14,
                'image_url': 'https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?q=80&w=1000&auto=format&fit=crop',
                'is_featured': False,
                'is_new': True,
                'rating': 4.6,
            },
        ]

        product_instances = []
        for p_data in products_data:
            p, _ = Product.objects.update_or_create(
                name=p_data['name'],
                defaults=p_data
            )
            product_instances.append(p)

        laptops_count = Product.objects.filter(category=cat_objs['laptops']).count()
        self.stdout.write(self.style.SUCCESS(f'Successfully seeded catalog! Total Laptops: {laptops_count}, Total Products: {len(product_instances)}.'))

        # Create Sample Reviews
        sample_reviews = [
            (product_instances[0], customer, 5, "Unbelievable build quality and speed! The Liquid Glass trackpad feels incredible."),
            (product_instances[0], admin, 5, "Our flagship workstation. Absolute perfection for developer multitasking."),
            (product_instances[3], customer, 5, "The M3 Max chip renders 8K video in Final Cut Pro without spinning up fans."),
            (product_instances[6], customer, 5, "The 4K OLED touch display on this Dell XPS is astonishing."),
            (product_instances[14], customer, 5, "ThinkPad keyboard comfort remains unmatched. Gen 12 is super fast."),
        ]
        for prod, usr, rat, comm in sample_reviews:
            Review.objects.update_or_create(
                product=prod, user=usr,
                defaults={'rating': rat, 'comment': comm}
            )

        # Create Sample Order
        if not Order.objects.filter(user=customer).exists():
            order = Order.objects.create(
                user=customer,
                status='delivered',
                payment_status='paid',
                total_amount=3698.00,
                shipping_cost=0.00,
                shipping_address='100 Silicon Valley Way, Suite 400',
                city='San Jose',
                postal_code='95134',
                country='United States',
                payment_method='Credit Card',
                tracking_number='NEXUS-TRACK-99481A'
            )
            OrderItem.objects.create(
                order=order,
                product=product_instances[0],
                product_name_snapshot=product_instances[0].name,
                quantity=1,
                price_at_purchase=product_instances[0].price
            )
            OrderItem.objects.create(
                order=order,
                product=product_instances[3],
                product_name_snapshot=product_instances[3].name,
                quantity=1,
                price_at_purchase=product_instances[3].price
            )
            self.stdout.write(self.style.SUCCESS('Sample order created for john_doe.'))
